---
language: ruby
rvm:
- 1.9.3
before_script:
- git config --global user.name "pchw(via TravisCI)"
- git config --global user.email "bump.luv@gmail.com"
- git remote set-url origin $REPO.git
- if [ -z "$id_rsa_{1..32}" ]; then echo 'No $id_rsa_{1..32} found !' ; exit 1; fi
- echo -n $id_rsa_{1..32} >> ~/.ssh/travis_rsa_64
- base64 --decode --ignore-garbage ~/.ssh/travis_rsa_64 > ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- bundle exec rake
- rake setup_github_pages[$REPO]
script:
- rake generate
after_script:
- rake deploy
env:
  global:
  - REPO="git@github.com:pchw/pchw.github.com.git"
  - secure: ! 'SNKwNmniL3YKerFKDNsyjqZp7GE6acFElOLLfvHhdac8vbFs5tRMGewnhOvI

      W71SZXotudjB643Bq7tZ6zT2Fvr2Mh0QMniaDqxHui6eJ1NJG3seoF237qNs

      Y22y9pfZK5Yth3Ir4glHWshH8vhT6e5r/MUvL1lnONO7otERFwc='
  - secure: ! 'AkIqiKmFWYodC/RvKHk81QypDe+qfjZhzIRwBSyj4Xix3Pl9AiDv0FJlJZA4

      X/4FA+b98IPOgYA/Ef9BFwuqoIW9z2vjvJLgcSwAWu7EvqErjFt3AuYpcmDJ

      79TjAZ95WUlx3S4JuXvFbVjKAe6DvWo2ma0JAM4h+ipAhQW5za8='
  - secure: ! 'OzSDSGCAhARRnc4nM3KlKXrGM9fdYaOADcyWHg+QetKuBMWfQJBgcXG1LvQj

      9MYup8LLhKmRBnPGojIUSH6HsineargEFncYG4tTvugTjKFgDwdpD06Bqy6N

      XIJDPPRjb6Q16Iu5MJidwRX90JB4aeHl8qzdnBrBzyMZhIhE8VI='
  - secure: ! 'qVny9mOy3smjMZCWFxjF47+3FNwKc3lRIvwZpRvtMVfILTJXi7wP/YbPxXh3

      ayi4FPXJVeyn/GMO4pfpsJPayACLcNYpJze2CLkipIYJIovz7qdZWLiVJl1x

      R4p6ZcZrdPk1PtELfM5KqLIm61SbPvZpfuRbM4HcGBL6KlvLG1w='
  - secure: ! 'BYGIUhSMFdC0UxP5FzgDeMxredvA0tp2WD1NaBohEhXBIb/X4+xnl+CDTm6Z

      p4zeZ9F0OlMnh/P1tkC51ckoWSkl4lReMs/GNLgnjKrsAfike5pgqRXkg7gs

      nBeQMFPguAB7gcjG81DS8WbRphFcz7Ll7IalX62y7ddw7qi29Jw='
  - secure: ! 'mligyijpK17xeWBvH+6j7quVYHdd+il5ftLk9oe670pKv1mKjd/a7o1HUueK

      gqvuUkDLR8OHBDCZSqw5oW4fRmmskxbQEvFI1qDU3w7jzKgFY6fQNhy/pB6A

      hC2lejcbfH6Fhqhd6QVDubzyCsYDXrQEJ1iBLqjVUGzk9/CzxCA='
  - secure: ! 'O7xFS1IKcI9RlVYYpjuN7/Viu2zcCv7dbJfoQ3u7b36J0QbG4S0gMgNSHCx4

      01Hu5QMfVWl0CtgPRt6ArPF5QObXN65W0h4eATukqRAZbqIrdoj6j+W7nVDk

      Gixvu6ikZBuDJs9MXUGTppyqVaXJWzen1xJCldXeOlV1+a6ii4c='
  - secure: ! 'KA230tGJPTOuyuSyB9lO/LsGNX0Lpk/j6QtO3GpSbI5ek0e2mtTdIPYLK6Nt

      ks/uKx4AWjo+4hBzKIf/gJRP/7svcztDu8uWz3Azl8m7EOF56Lws088sKy/a

      2GfLad404Mt5RbUagFcj7t2K7pIUh0buvz8cpWQUfeECqKJMZYM='
  - secure: ! 'VjlVOB9Dhy8Q7SGzt8RWNtoVtYQ3XBP4ylIT68Uf9j+DWRqoEqlAi7jYl0kw

      03YLrs3OkaaoeeDWQhxM6oYo2uC5z5eUXQdqweAOG0au87pvuj5wwbRxVJE3

      7/3v1orADbvMdjdDtd6Ccd9ADvYD6GSgxLEMeVJGwnlI5ZAlzRQ='
  - secure: ! 'cob9+Uk/4LAO/GBRI7CcLEhLXznxKZdirPPd+S8CNH50PE/8TJ+C92AXw3AN

      8WSMP1gHJukdokp2/85kLp4bDAZhfYy9VAW1yriuBVnU20Yv6z9CobpU0qdt

      GSEcf5l2MehSZgo2Zi9YTM2pomJuNJ/a5Y07dltClljpMnpf/3w='
  - secure: ! 'JfmopMROZp89+TV/uIz2H5FyBe05eeM8MZLhPZzsYgivbgeFxyz3Il2xKdTW

      CvNJ7cHRJ3jZaHPrGxCaITxM4/JFkiVkMJGuP3Vs+ii79XIblP3uqN0i3WB6

      sUu4zSPac5kQUrmRX23vXvMaf2JrM/wYdg5KoLqdoeuTNx3/COY='
  - secure: ! 'Lgh790cOmh6mKIXgo1uCqxoBMOd/1RamehymrSS/m410waECALMmWLjkQwEc

      3gZddVJpGOTKGWqsb0zTuZm0av+E9EuGdNpyQfimbip9/c4r7zYzev5UUXZY

      xBkl0lB0AeNbeUpiW972ZDDamckPpoX8PhWCBTGUVHdoQKL1uNA='
  - secure: ! 'BMp7rbIkGyBUkFUMiMkVwxZS1hYciL5/cvKpkFpJqAB5d3xmUdGOEEFVebsI

      xvzE4HVWPBtXStdUCFEamnNyRxeVlr7lDKpkHe8b7UKyqpSWc+KhJ/NTSW5N

      3HkMIoCf4QKljpXYPnmYrVIpbwzzEOeYga2eJaSQ04ocmzbUpg4='
  - secure: ! 'brIzxf+HYvnK77cdIvmQ7wsWj9s33DJBkt2AAItwbdKzMm5ZZe/3pPATT/jg

      I6v6RrnfYXljQnijsVkjhbq3iQW/PAUvUmKDhE4utw9+7gFc5g9sURPkIoSw

      X7wIPamnwU7ZeqFVnBQOixeOdecYSbH5SnCaCexdMU1e0Luv18o='
  - secure: ! 'gPO2miwIsA7x+N8HtjjYLARN5+fMjnETXXjULK8coSnB87eB9hKJnsVO6erd

      rW8n2JyaucqtNl0HaeM80On6AOzZkXgFgiRi6wXZEDicPCqmx1zBsKNtktBX

      txvdd+Lh3Xu49CTZRVPPnKb/kSdh5sBkq4Knsm08KiTbooRnrno='
  - secure: ! 'cOLOcPf7e3JkbtGF3ycfUKrOChOD6cVfucF619g7OpZpPcRw9CaycfeVZUHn

      8wGoJJJWfukJda8guTzGlgV7DE9jVSEyCGxnptYIJaBJTVn2H0K2fMhsQd44

      YK+LO/n3XICE+XkTH5bs2OcZ5TCzJh/5PLbJgPaY91IvglsxFOw='
  - secure: ! 'akwO9jdNbm/hb2OUCGV/pCGUHF9nvaU00VyGqLSR/H7bfD2pTy3EOaKiCMwQ

      o+Dd0EH5jjgsKFdoiXmsqsru8UFmbh8SrxgaX8UhnVGv30jq8YxQggMG3jvq

      kXQb+V1BkMxqy/Yq6Vkz+u7hQm2dKsoFPGwXCrCMS9p258D29nc='
  - secure: ! 'WaVUjM59PEmHTA9fKB4MbZWxlf/nwCYvCSncYFxIh83pLGe96RGOLtaJ7Sv0

      lXQfVl7yOtstQ9RGOLjQpFYG+hGMEeLlXD1RgPqHo/GfkoXreeTpmpQ4OArF

      azPPMX6M3k2QPoGGfHcd52VRdC3jnch7ingKokewY0EeNhVi6vw='
  - secure: ! 'LMeW6t7hMF5ERmjxeouefv33DBWG2lWR02ORI26/L/hWpt+fzahGUiJ8wMZe

      qHtmT7sI9zrd/k3yDdZALgPDlgSiayPWH0WnbR/x4EZ3k4hjdMHbqN3PTLTc

      pnNte6ZXmMkqCPaPHJcI8HFnjuFYhQ2MnPo1E4+YrjNSkzJNQe4='
  - secure: ! 'aRpEI2+TOB+WC1s7uJd6swcEmLOt8D8pXEh0VQ52lD0G/8r2HGHkxbgvH4GY

      6cvMUwnzJSTiWIRfDF3qznK7avk6EKwrxj5jvjhQB6dpIjpuE54Leno+X9gr

      dSsp8SOzrLpbd5Sn28TJ5RpjPxphUxcOfRRbor+wFMhc7QQ1hWM='
  - secure: ! 'kWPEpwCJ+giBMQ5nuz5ga4aLjpU8LV2ZdVh6xN3zv3V4JKSCl6HApKRlTJIS

      hUNWdJ9yCNUtIi8LrwtVvhqqRNil2gVyLri+v6p54wJNI/MQPgt8IWr+s3LP

      t4+Wb1eZxFrhpHplNKf+PNj5ix+jdd/C9JI8BY17vnrfvW/POjY='
  - secure: ! 'mD4OriKxVYZdRnxuIdQwScUtF/Ge70Uc9g9oFMx2N+Z3dtIcnAtjL6z4Rz2T

      mYLZ5G5qQPx/sGAwp/QcsfKkyp9aPHlEivY1MLf0VgFCv0vjlO6g6vaDiFzt

      6fy1xdQ6wJ/qj9l6qPv13GG2u+BPp//TrxGRJ6yAQx/yFMO2OIw='
  - secure: ! 'Z6A/+QR9h8wbtG2T/TMvwxQFtbWI6aBVCs/wafPsBPXZnn6gxDaBXjN3q7TD

      2ZWSpWltBCdSAvCyYTAVR/tCweO3p5cGF97SiTO5Uwp96jqME14orxc5dIGR

      gQatlF4q5cPepWZcgze9SJSXh19wOe1FTaAkRL7sr1Q61zmm6mo='
  - secure: ! 'XNuyzQK2cqcp3liZ1jhDf4x9cCTr+nKFwR9LgBdYKkmQKSz3afwZKOOYziRJ

      yMo7qYfhbuhoUAMJ7y/1ol8zVDQTfCcJq3lO/nB0hvJ7A6QP9q/MFBzYgcss

      If3bmkiy7i5LpYGd27gs5tXKo+bsUHQj7+8Z1puMsXA7clCjTZQ='
  - secure: ! 'So5U2Q/SvMm0SbbXAghnKt/Na4/k4/xiv7FD+H3MsxvY1WZkujh978ozty7r

      VYbrN8gFjtZInWdj2zZFA+oxcNedK/D9Fl5aHYIfdBx+M7PS/QXkfFEDT+S0

      aw7oesz4U/QjDA4YWbOM795zgrHMJwMjkcs+tjCBNIK/iLcyLFA='
  - secure: ! 'GO7mfBJ045i9IdMwStwYAAMnc0JL1kOnruNYS9EKtMqHyC9lFzI/MyUxQ9mf

      m//BkU56bBKmgWStd8rL1/rM26RbHcJcMZgM33yxJGZKd9KlS5VTrw0U6MGO

      UQdWfG60OOu7wvu4E0/q3pwGBg1AYMThmQu5pjxhiX31MyJw8gY='
  - secure: ! 'a2rl24LAWESJQ7QRnZdIHXYr0Cz85dKFnV8aJ7UlEn5NrHsBXUHCJDgXjCCC

      bhJgx25bVp9eObS6DjhtOzObg6JdWgz0wsoHyrNShZuC/N/1uApcvCwnFNp7

      r6B9352bY+HzOVT5wRFZn5vi437jCZVl/Es6NbbuEfCnTXNqWao='
  - secure: ! 'lCXeU32LkhLqKMHy9BXTcFJL/cNZfZXqon5zGVtrJ8xsgXletRHUsdiCJT2t

      Lx/gVpmOvTOO4glPZHDKbBhXMPUzAzXfK8bDrVK+ObjTUIvqwxXblFmrhD/3

      wpORm0pBnlbXOGvQaW2Dwi3olrrmbD0scdojpvKJjkljNIRWx7M='
  - secure: ! 'h4w183ooYf1pXWaVYxisSMJzrD8J+fsSOTcXWjmOA/kQV/sMBF/74C5q18EF

      WCvAn3z/xg8HxIAvIvtcNW86ijn+nksZC51517F90xgokq4e7J+eGS+1yavA

      xRS0thgMuCpMUP+agBOUlVusO76eDW4XWw0SoreNBk/Iz46Z8Ac='
  - secure: ! 'IjNeA7J5MIYFE7+q7010f2svWBhum5giRmpD5Rl7AV8pSHMwDtU789kuPOR+

      S+qD1OCn2ZILXbckOT040sL3yCrq8pRQ9IOzBCGHdzG2CpNm15nw38Y9ftA0

      xBIIovJxVbqdEaSOzzAh5HtzL+qELUsGLJpAEs8l4ezA2RI1MpY='
  - secure: ! 'lIwxjv1Whgbd70ZS9D2apQcnyU3/TZdAm6XjlAV/Kd4Bl+LdnAhJrCigoB6G

      KZqBTY5y5qEItVnk03Jjj0p8UFifWdeas8yFHkCMvZG13JGDmUxKHpcPFie5

      y/dPt83AIGcXfufkBuNwiQ3ypOwqNS/n7VrPyzN7wbNotpywZGo='
  - secure: ! 'a06BDS4g/rcOnoC5S9gWu74YmHsqIl9BEo9bDV1XIGn19ut9a0y7l5xZZHLZ

      1MxkZL+qeCGwkSBVN+KZdelKwZ8SgHsfghGl5Qt9U0VkzlnvZ8xeTDptD+Z3

      Ldatcj0+8MHFr4vvNW22Vmi8gSZGGZb+9/b5kL8K7dlNVsU2Z+E='
