---
language: ruby
rvm:
- 1.9.3
before_script:
- git config --global user.name "pchw(via TravisCI)"
- git config --global user.email "bump.luv@gmail.com"
- git remote set-url origin $REPO.git
- if [ -z "$id_rsa_{1..32}" ]; then echo 'No $id_rsa_{1..32} found !' ; exit 1; fi
- echo -n $id_rsa_{1..32} >> ~/.ssh/travis_rsa_64
- base64 --decode --ignore-garbage ~/.ssh/travis_rsa_64 > ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- rake setup_github_pages[$REPO]
script:
- rake generate
after_script:
- rake deploy
env:
  global:
  - REPO="git@github.com:pchw/pchw.github.com.git"
  - secure: ! 'KS+LyOhc/JEL/2W2g4frK3A1X2Q+ANl22u/ceS9JyERPHzLLN7+lm0FNd6lr

      3fK8eg4mS0kKyKJAf95CbD1YaAUbhNLhvPfPENAxfOOQU62Aa47OJJYW6bEu

      PIS4Z8lbmGXHwIb8TvZBttm/8IQ9rWVLTI3AaxZcXwMcUYwLBo0='
  - secure: ! 'ctUJ26gTDZ3Lm0pfyfZdhMbIFpiF4q9NJg3GMBtkbsljJWm5ga49EhA7zsbo

      p8giTKCYBfq3mbFb7K1Kkkr2N+3dygQRPqLC+JsKJnBRSwpWzyZT1I7KQ4T+

      Zl2nTh9UwUPxjjXqACOl3y4STBqz6/GKJoMDxegPDsFkLZZIJHE='
  - secure: ! 'HYoerKJPrIYEvGGsi9flTMBc2s0iiXd7kRhJE2zuoD7PTnxNR8p969+E1sZV

      Smq+S4FjuXrXPBg5wstGYe7IAlEkq5dmHLpQ20Blu73H3o9Ee3kDQ2goX9hR

      RNVP5ld8PCDE26powQDtX37pGuWua4uTvDtmeux2Ofkv/AxJ8nA='
  - secure: ! 'UQrpo0jX/4xhAtuWGt0Q9euwowxsTBeTuN2qHhgNtZ27oCSpfTJ8IFytYE//

      GKotogYLQTeGjwR8l6sIkWwZe6lfR5RMYLTTylpZjpmHZwn4ctMKvtWR5WRw

      ajgEM3C9LqVZrdBspkUu9vt0v6RP5Exzym+uxtatqyWE7YmnmAw='
  - secure: ! 'SvzRPQi54ovbq2Q/777plhi+2AgLbfMHqVHUoUzNdzee2QSQvfEIxGZTJNlX

      oboEEZlJE1ZwmQlXOgA22i6g/9IzsMtt+ycPe3It3r+V2mj1YxxkHrTBv0Vc

      a6cck76mT4be/FDmf5VaYNZu54qgzfuep3Oa8fuk2KFeli3LdM0='
  - secure: ! 'UlBYKji6hmVzECJJvl3ilLbnxO0uUHat0mdWAFb1X9CuPRFBYp9hQUDtozMC

      6Im4VMf3wpMA1u1sCWGaiWkF42b6++EtkPw4ol4Jq3eQtmsLc+qaEKohpHyb

      BiNWQd4dPsV+jZP7jdN4k2EblgceQPCBNrDWVdUlvnSuWG1Dkl0='
  - secure: ! 'ZDgygypilyFKCumX+K9sEb7zYt46DXZ4PR5LzP6alhYoD1u0Dcg27IAIqXe9

      kHmTa9CfStzs7653LerkzREfbI4b3qy6cXCtVz0krtV8CmgXHzSRkNM9sbCz

      6PQSnMnekVtQEWi6+8zNmkvxwn/ClSRv785KRndOp/pobqzx0Qc='
  - secure: ! 'ALu4Wzy5jWO8ZG/nHXvXHH7TXmWEKHOcNC+2R3dKJL6MNRXPkPxJNMHqHh+j

      M8ZpQP5uMa8ynh7/Fbm2O6n3DkhDxU2HWKzABkpu4e1eOG12oByW3UrUSZjQ

      kJ5oNJtg+30oc3SALloiVw4O9KhPQU3cfxp3yjJ1KfE/+QRO164='
  - secure: ! 'YL02CsYe+Gr7bWCWt4e59EnZWqIL2LmHwWYf1ZUKa54M1as4JmGvTxd8uBJX

      N3AJ+Os/p7VYC+UixnE3EiF6AeHbCoycyAffWLlQ39v/OGR/Us05asRcQGzR

      zU3KlDaqF6YczGXjPMglvgDOkQ9n66wQluPLplKRq/DAFU5CPIc='
  - secure: ! 'CQJ16DcXFKAd6X49x79QzXHT0xP+PfIuH+ncsugGGAWOntKyhQdZMRmnzw3X

      ltUUVsBldfWSw9gsIKkKctLnhTGE+wZIpf19EssqJMOXfLunrnM3NrXK5nJU

      Og+Kg3zcQsKAOWkrf6QRPxWQL4ZkhhUQs33/6X6M0506X2gH38g='
  - secure: ! 'OpFkqSYk1JOH0S/VtR9O5Q+n2HbnwjezYzKyhs+K3PngTcTtO+6TIx5hhNgU

      JZ49L80wIK6uQkOQEtj8JDVfUk1YcFuiJspwZjgcyleZqznoJ0XTVDbrba3O

      Y+T6bkKRSeDQQ8rfoaDTcOyIK3Zs8pNMR0t+41IO3+mSM8p16OI='
  - secure: ! 'LpdhyWIPhz4pS4FG65xDabkHdWV7+ykOsl4aZuU1G2h6hZiGbH682mbk5R3z

      vfYkR8grxYITS+iDXwxF6k12MnWtK+8evd+gToWalU8rdro7qgqglqySdBI+

      5A5YWo1wwSEZY45lC66TVKV+r9sI+317od8MeT6pM3N7VCVhPGg='
  - secure: ! 'deDt5PGR89sphGeed8tfSvWqEY5qwXVSGB89tgowpS1ufBxO5KDUTQX2BdkE

      YliYgjxyV7NvaDfas0gmGg1osNbwURNxZFsYSONM+V5NEB4o60exW1/mBV/r

      BmnDlh/22/EKs7x1XkdoOhRXa6QiUU5fb4bnjFPjtmyjC1DzHnA='
  - secure: ! 'PpsyySKDQT5vfgCq1HfSrRELm10IqInNAmT5p+k3QAqRByfg16tkanAJ/nMu

      zmQozDABGAsipkqqOFdH5kt4+XN4K0D502tLDPhfMTwIbBtCIjR5lNj7XMqf

      bBt8+HgU3rqDfaXiQaeMyoLS0Ias/D+W9GhTcsM203cEnrSdJ6Q='
  - secure: ! 'GIPai4Vrm7XHCH/xbVfla8Ym+vrhKSZTAEntYPuVb+rplq+cXMJ44W3kXQyA

      /RZmK96X2E9tTuOpSV7dE46bffSahZw0iJNcao3AV0cWUehFx9r62YGZfou1

      q7Gug4SL7C1MHSULVffRR6fZfIJBwyjj1BWs9dewnTX0lRNSQ0I='
  - secure: ! 'YT53Cgxu3lYOEGw6MxSWXHdU/ke0yzEJXihRZUo4ZWaFEJzyClSWokVww3xF

      hzOuqp5zTdDuqsotaX88AEEuy7QvFh4vagOKV1vvS65+hB/+bmLdZrf2Wzs1

      ClYyx2GvELusUIlQGahjYhuSMwnKIpMgSzkpYITR9RKG61EsFOM='
  - secure: ! 'YDAMK5cBo+kdnuTQypjeg+xldQKwxXMhjfKZChD7WMb2nXUWZn01HwLb+QCT

      LZhyHIJ/S+A1w4a7v16LpCsnvNGI/FLEDuOTZrnRjaQ2stD75kOGe4mclwcJ

      DV4Q4BiWzxX4SBKshAHpzwRdjgprV5q8D4vB0v2gf5zu3Ouc540='
  - secure: ! 'PBs8O1whtsZTQDvevAlrajCEMrdR1preje3krZGYyyncMhlOY3/5sm79365i

      zr50AxjVqP6FU623EU1324/ZNHudvcwtko9MsCEvmR+xqPDAIUDsVBI+35vp

      Rub+VPYSWMs/6jc0fmWb07Wi0isxqr6egmDXoIZE2azM51UAh5c='
  - secure: ! 'QKVKn9n44c7PJl308Rkmws5h7TZReUKP7RLY22mZSQBCALWw0s0di7yeLVGz

      no2lhdg+7quWRLb2MZrD5V3CMW/NmclTf9jaRDK6sZBLx4VAkOYQgTgyukOp

      HcWa0YaUXO1OgqBPVD97sQ0tWrWXKPT2/rFbPFAF0vEGK3I61aw='
  - secure: ! 'BRc5NK0gu23fxCf6PwZLInHpLGIe7fLF+vGjvDzoXh8DNK13TzUZ2ZpDEX+8

      5b9a3JV7QJsaqaPt6J9KLIXVGAKvxUSO5ZFtADbTwLYbkrEyyVdfGe4+s4rb

      DTcNJoo/Oj36tPN0yR4nIqjtvI5VcVkTPLAFM5lXHNIPuA5TE5A='
  - secure: ! 'JTFex/H/1S4gp24Yc/NBGbqtog59WfLbrKjPo7GG/laI1e5wVjJYJwb2hoQw

      e05kytTZM1Ph/PF5yxgu6FMXlfYv6hpe1bNz7+E7dSOtqae/dG49GWAqhbUL

      KczbWTEM2irq5MqvE5WJ5ptMgllf3EZu00BqHrxGJMd0gS/N33M='
  - secure: ! 'S3BH0ZC5SVLOGCIwq9ypxdmcNZjvTz436ujXLFshUA7kSzakvIuS7UOLndom

      gFj7b3eGHYeIViX806mbTJWKwtT4GWsrTXQOJOVTgsJ9ljzdgZuV0xthiApU

      haKRgUOgAMRDXl3ATHW/ubk2y66B4N7cmF9jVFfekQ09e37cRQQ='
  - secure: ! 'YR5EKRxUKKjq/qnra/Fk1EHafs7RrINI1U7lpQJ2d/gTnsEKa+ebIEahO6yU

      VWbPLH2iFR7mpu48xdS88+jpkpgwXb3XMDmOP6WOn72DiohgdhVm0WIxG0Vr

      DPe//oh2tyjk52BDaFlE3etpl9/aNChBF/X676/vKZ1wLhBeGzY='
  - secure: ! 'T6jKXS8E40ZH90Crg37tPcz4AzlO2EP4DfjRr/jtfwJHrvlrFVe/5SuzqPzN

      e6Q/ypIbL1mG4ZndwrgQK74QEk88w1AQP7nms44qThVsUBHa0DGDkU4tgCoc

      Dl4IGjT5Ggyggf/dIb2F2tRR4JlHYUU5EBQHwHfFqE2pBjStu1s='
  - secure: ! 'FaqJDBIR5Z8pEws57NuYwZvntCTUk0u7YHJGEM3KecNmvZn/EQ2/9VOnn69O

      b1ikCQoYjrIL51PS/CtvrKYB/txfRifIOzTMhczoxrqmQJWJe5ooPW8o50l1

      siSy7Hj4nJmmc+CYM28yHXucJ9Lw1VkDKUexxRPVVSOnUUZRzCU='
  - secure: ! 'RJaB4Go77XeHIxW9p+E1RBjGfhwMnb7yX7hO/jdocNAf8l6+P5ThRLNq8yCb

      bS3YhPFVeucHsDPomiGZBVNi2nIh2y3O0py49Ty0vz7QmrrIueo6R3eUJrbP

      ZWN8nPs7UjZnObkIlpAwhA99VzZ/2J00K05jfteHUbFw4qfJxH8='
  - secure: ! 'elrV6qeKkoVWVdXlYRRtXO67epUO8V4tOuiVbvGwPRubYVHR/1U9FnF9u+33

      Xh8Iv30sgZEIGwOEMHP+1xIYBDFg1ac3NXhfx/hwaa8tVj/pNWtSqgPVpOVa

      un38WvdBOCruPSFNf9CTYX9NOtFEtuoXuszuO7vOtP7JY/2lrqA='
  - secure: ! 'g4Cx8MDxCm7SqqWTZJswzSthG49IEI3G9MCpPGKbCEFQp3sTbbAMzZhgy7x3

      83HyD7MsDAbLZTe4JVZWGLAuVDBbUJ4Ll3XId9VtarKzadpnEvjGaWAa99v4

      Qlvk31In1z51Yaz5aWY4syZztCDwAmgxeX+QgcFuM3pxJipZ8CU='
  - secure: ! 'ViiyVefrlbFmX0fMw5hdQ27P67o07e0fCjJnzh7cvX/9OZ6TMKvKtp3FSv4R

      UijPE4btjdQeKKSytkQeUoZFPHBWfqiT0K+KFeZFNn+J4YbrbogxKsJRDT4y

      JlK2U6nHRv95nzpjTdCy1/h3KacqOSIkN8MGgie8CKh/6RKdQnQ='
  - secure: ! 'I+fFs2hhlyFuLOUJI0gwmr2s06mJxUhUCskfkw+XapbymSrWNUl2rICRjuX1

      lcecvhNkqSKVBytdljhIUzjQdbj8EkGsGIu+BFduZwmrGJqjZiy+cQJrPF1r

      yVQv9m1gzMBFOXfiPMfQuXgetZOwbgVL8T45siF1z5xZTz74TEc='
  - secure: ! 'Zz4ikr0ScGfoqrc0Xi6ohxlp7y0V3niEFR24ZWatwxZeHdfEjxmhhN99Juxy

      MnPwYiKE03vyKadIvJmHivQ6GXraiZVVmgyxliSKowXyqv1i9j/pc3c2FMMt

      sl7FS8CjoGG6yRR+9TP5ywXYGY/dV9crcwl/aNuSArFWjpIETyY='
  - secure: ! 'CW/bNLbnvfPXNFtfNweiZ+nAvZGC+AIIBoBT81xxFg48w2ztyCxsW05QZPw7

      OOur8/M/FKOUDzwAVv4oGeLbAiG6dkDewnRI5guEtdWyMC0IqKuqBJxuu8x0

      3S+c8euAyAyo6CsQttOkq93r+XhXkhkTTEwLZt4fRW5J90/vDW8='
