---
language: ruby
rvm:
- 1.9.3
before_script:
- git config --global user.name "pchw(via TravisCI)"
- git config --global user.email "bump.luv@gmail.com"
- git remote set-url origin $REPO.git
- if [ -z "$id_rsa_{1..23}" ]; then echo 'No $id_rsa_{1..23} found !' ; exit 1; fi
- echo -n $id_rsa_{00..30} >> ~/.ssh/id_rsa_base64
- base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- rake setup_github_pages[$REPO]
script:
- rake generate
after_script:
- rake deploy
env:
  global:
  - REPO="git@github.com:pchw/pchw.github.com.git"
  - secure: ! 'P/ZYAHgcjKp6LTvHnlob4d0JCQAfn0S3oNflFYMy5VkGRcJBXGrIlWRycKPD

      4fUR5nVlvc/EqATEMQJ6fR/Rkrb0/6Wj8ey/iqKlv9tJHp12ijN1ah1Ns41t

      ujjlNG6G9trs0kMCdQ6/aTDMqCeBkzmv8Px5cVpXdl47MjI2wrk='
  - secure: ! 'eXApk4fFMV1NIaUj1lQ0GCElpO+xsUK9vOhpdrSoGRLO0Sn9d7c70tacpfgo

      8Wvmmj1wkPTn8hmjHHSFtEuNUFv+5L3AAX8y1gi9bTTL/57Ps2xQoJ4dQrb6

      6F5AexsBs84IvMRBi3g4AU5/kTcXhM5Dqqgz++axiuQ8qtUiUnI='
  - secure: ! 'PUAdkAcwfjXFm0fms/szxly7tZ2rqmI85etW3KE3dbkzADBOx8264sWHYrNw

      hnGiS/ZopTsbm0nlk1Wt2Z9xKPJxvtrZ2N/6XL8HFzqEivuVxGNkab+xfpXM

      UAIx2tenEj6gjwrvtDmLEsxmLgHR4zKemyHz9p9Cin1y9R/IVlQ='
  - secure: ! 'AHFQsOae1ZdPhxAXJPlbXWxYJEO+G6RvQl9FoxxHBDhin5gZ/L23YZfFl2FF

      SOPL0bw0bUN8Yy+4aCCEsxCjdSUra6IJgVqG/sSDn6jUzin72VrvghaaTrH+

      QRunLpTdFAXyeikXJkzapbe+TipYVvEKQWXTrUwt8JP8te5atAY='
  - secure: ! 'H8GdHJi+00wu8RaICbr9iKR38dOnNnF0IqdIdk6vruW3njCXH/MChjVlxwED

      1zANOQW3VW+PWBaYKnjUeXmO5ZjpuTzfWU3AAOzdAYOHRYNFakCquqfXxaYT

      elyjaWa389frT2DynXDCB9+HJR+ec9JMX66m1k3D2/u5PRrBqE0='
  - secure: ! 'GoAIv+4fE0fpS7xxz1DT0vmJxXQEUNg0sQBJh2WgRSs6DNeWsYfaHXV3D8Sb

      WPO4rSP+bWOGYmcFMPcx6ZWsvm0KAE8pQoCJqW22asqXsSPyPzC0jwp+EDIl

      58SYKhXc5o/n0yCw/3trerOqiKfJlWkPzo6DjiSgOHyzU+w2dlc='
  - secure: ! 'YMX20nrdNQ5pK+8oqGZ8JYUgIEwUTS2NjmO451H321NTX+Bd05izC9/lUQQ4

      tOi+805JfQQK8PIJvjj82PdDY5x5UClQinY795F04+7a1ZdLCooBjx63yHKo

      dKUtO/lAwiEPsk3bvOice7izkF9DEthJKTtbgWoxAmxF3Rzrda4='
  - secure: ! 'airBC9DmNbeXq/ByUCd4DcTkto5V1OpmRG8rYy6MDpbAp7aLnVQGBMqA5hI5

      feD9Mg0dYvkpxrNXjc8ySQrbn+wiIjn2xF1FrocbTkYeQ9g58YwcryS20jr9

      2NFnEaijFbJ505v44sYmmUPvtJkPC+iCGMKdoAJSHuhqYuzlavg='
  - secure: ! 'bv1Lt2K0L7iYL6PL0by/sG6wToD4D9hywGd7zMHJFPMRNS5QrwnKhps2AZeV

      oTYihQvfH12lqdfJlGobb/E0RjrDg/zU1l8a3c6X7nMHQoKa+I4lVJf0T22f

      Og1aaZJszjclIUbY1oe4T7NnAwxqIteExsiffPprS/00PHljoPk='
  - secure: ! 'hiUoXd7UUWgUVE/AFEOJcfTkY0Pu91bn4iTy9Itf1Ah8FzOr+UPO11QyBEtd

      r56BcxzJ/K1sUUmbuNEiDovX9yxOy9tUiq3bbXG9b+t7M9FzFOJgtenXdGBW

      P3VKvdG3Syw5lJ5AfXZLObp92d2ufv8r0tV1q69j1U3+L1p0rIw='
  - secure: ! 'N5r6XfaeHMf1N/ft94DknWclrrXNP0c6A/jcaOGbzF3VEm0gmzcnWMz6IWBL

      mZqhtzwQT1jdp3OIIyfJFQO8u1lJvZuEBLgVLPjYIeqqYHHR2bjcnT7nMm4i

      D6EG3M5k7SKPsdxPFzYrVOYdtUqy03mo2h3EQCtSeTt/jt5yUzY='
  - secure: ! 'FTsMr0k4t8jK9pTKvJ3xnR+Dan60gMfLe4GrFAjupsu/h4dThnsI4ncmc0jQ

      cuvE0P4ZYhOk0KLOQE9SBYEMnviLdB2t+eCZ1pAETDSrwsSUmEuLuvAM4O2d

      +bvampLdk88NXk5dWdHrguy8qKQZP7HhJOVcHP9CBOE11NVLyZk='
  - secure: ! 'XPcwO8B6k8v9II4AEo5jKm/rnZ4B7yAF1durZmyomSw2+krm1+vYWR+FAgEP

      Gzf9Lhdm5KVx0gEy+jOxPu23lcAmHlEQCL2ZlknZhwX1GFaL08zC3ykqn27K

      UeqHZgwcpTsrtrMcoP4bhjekXfuw6uoggviobpbvZX+UeQEbU38='
  - secure: ! 'OIjCym/bX0qRR1xVXlqya1p+1hUirO/p1N90IpexDLnWl22K5t9mKyXLXOBn

      us08/Fbl1siZ8C1HtFHuxdIbRjacHAPBt29p3Ze6qT7ehlwOqu5Fr2nl4eut

      EG2P+q6yS38kqR536d0EtT2h+WQpFxLS98a61zriHZKsDzQWzTg='
  - secure: ! 'ZUmxVpVhTV9Ovh7XdvrXce1hahUMm65qHiP4whKwLgzE39H7obyLGgfg1qPq

      zNHGWB14wK5toCGmPKO8V2nXDwHuyGUyASzHkLwQCAZDYLcMJU/aH67RwNHQ

      wGeyQ/CnDwlGjvw0znUiaf9REnSJRwkN0rae4Nnsk4h0erlZqHU='
  - secure: ! 'FYNaYOmS+5RwuhW8vz6emWU0M2DMuWK59NaDNLNmKwC5sV7tBomeiKzrAsqO

      UIK8kbzQAWrzownKRcq2FIOfg9MuJWpILuLCjOnxLT7hyJCFRD+SFiTzWoe6

      QwT4MIRdrFarX7A6Rb92Fjl4mD6RBGmR/TdhegEzuLjKo+FlUfU='
  - secure: ! 'HJhb+ikcw5D9/MWC9f3bJ/qRcNhw+C+s63clLW4NecJ1Ki2jt08WqDiSvg6F

      b2PKQEYdX51olYkaenGNM0w16yRUAGZSeXcW5AHoKIb3Z38HNC+IkQqVHLC1

      lg7kL5Ry5FxNjn2lhQWf4yRYFxuLenafRhKEMRq0TBDAhGA3ndU='
  - secure: ! 'TfXq0ts+MF/aF8+LhT91uNedWR4qEz3yRSc7DrdwI8cQzWOL9yyL7sPSIgSg

      LrPfo9SXHdbnxPJKgx1d3MY6hv4B0HfoOOugs/twRxlNe5QLV/N2PYw6L0uC

      ddvFZRaocvs0Ld/GYjc4og78BnMtl3OvriS0w3QN7aRPqsI9pjE='
  - secure: ! 'TQj/QOqSVSgJBZ1CHVLuOegIYT6O93WkdwF+JszfYLYOkbGGTT+EcgOVk81T

      ayZjnm+9J6jYmLvxJr/kLaCAWSCLoTbyqMhw+iGumIR5Uksn2sDXTIDheXKl

      M+R3QKAOTplnATfTVvSVdfJ4DJxHWec8yr6jYtgfwLAvEYx8gPY='
  - secure: ! 'SgQHJQPXEXKQQRCq6yV7Fbf7FXIAazr0/zWRkIvlNzwsVEF8waNK/DfrM0Vd

      2JASgO5aBMwSF2A7q+vbj2zt//EmJiRN8aYwYjwAfkWUnK17w7Z5lisVoZBL

      sJJgbx1ihwBHlfeX6HFu2Sat8EKqdALISQCZw/XhDk40miYVBn0='
  - secure: ! 'PHo5WOjTyrOwd+omIkQIl56plMApX1kvxPIORMqUgfQC6mUfv6MmQHjzJt1X

      dhgH8YMuqRpZHiE/dBpoOZRgOPEExb8JfTVS4ThbQ/RPRrlfSI+eyF8DNTgu

      dvVj2wlit9F6ozsFjsKEri6PTT+8dRGQODl2NoUKuZrCsJbPm0Q='
  - secure: ! 'IcF6j9xnjyL7COdGb1luKqSiygU5EsvMa4jTqLYz0k3bURH2QjmJ6TiSWroe

      JK8Xt4mD5S+axfYszQSCBH8kkMGsS/DIoYStzIEXvycsmBdkqQBrcS3mxicg

      LWrvUAk7F7xdN19z85i/gzVZNIka6cRFrQAkNH2TDyVH6vjbGIU='
  - secure: ! 'fLY11P7+x0G/m9Tr8rlQT7gQGbWAm7i3MDHq6SXn27GgxnGX/2uyHIUWCJy4

      wPj5+36Q2EqQUqbGlEeafF4XlyPrX5CqR7C7nFscGUDaJAZHOTLCY++G45pP

      VmT5LmXIjRSLckjZma7NsgQqTr0kGg9HwEFqr1IoFsCz1uoJUYU='
  - secure: ! 'B7dbiNlqgKlAAubReb9n1xD2w9EQH4mOzsztTEBZuGLCZwJWbffNClmD6L7c

      CtmKEjBNumuSReCDxivuSqZrOBiWUW4sgkl0TWIgRAxIHhOEM1o35VhALtxN

      21R5vWEO7hkcsrd7XNo8zU1mPRMKOqdVfnbEGFn6LFFOKERX1Zs='
  - secure: ! 'AAj3d3cACG/rtZB2flEl9kCg+o9x0CTXkGDYIaRO7BymtFJJrZ0rF6xjSJOw

      0N11oyNCW6o8MxV/3d5OooenH+CqrOfBWfRvSCeDFKS4CAHtGDRYKmTF1Gvd

      etnxjlsDIXZwRmlqz/nrqcRpIh4lNKrWre1Bt4VY/E5qWPtd/+A='
  - secure: ! 'BCNpsbx/7DyhLe+Y6Ft+5b6Hmsmz2t1JfquCmlrCznbL+JZhCL8NA+3pBEjU

      qwoI0Tkl17qaZEMeIWsCUpSp4c5XKLvnI/uPAVHq3MR4ngSPLTpQ4DjpILXG

      US++5WhXxN2G0g6ydUnZHXdQM8zaNdaoT313D9hmZUD+sMMQwz4='
  - secure: ! 'AY4s6afAQFRmCEYKaNQIb7ERCpasWJidS9SotIY+rhMd3SRg5AkPYt2XYDgd

      Ngqcw08hLUa7aJTsqHqevyqjYNfnTaWYGfAVTcVD0axUec773aQUQENfOSeY

      xgyLus+Q6Z3VKQxU8DMgQ5+8rBMVVH4eY1rcaHrLdAqbwVtLE9I='
  - secure: ! 'YrKxKFo7y95Kz0OwwGEt0l4T4HvstyfFxlJfALilWHvwf8z2i52/3QI1aiFP

      sq9oqGNRUWZjKUYf5idVPt4mapgtFuYgpfqUeF5IvqCP8GJkNbGtjcaXaaht

      dLzjLbyvNFy/vQkCaUUmX8jJLNQzg1SyMDB7c5g8dBcMxDhlpuE='
  - secure: ! 'ElYf23cOK1xtt/8SqvXpyot7cFM29sJiQclvbux/pqHZhDDsDw1lAs+D8gYS

      ce/RuDbePSuJX6Rml0q2Fu7SkHYNaNu15qQHyB8rACuJtMIN1tpPJbza+9jR

      xc1w6cZkg10JifVBgggLSfJ+1CKGoBjFn3Fr0uWjfhuZjIcAH3s='
  - secure: ! 'RV+/VKBi474JLu2Hi8X0C8QQnEwAFHUfArbi7V+uFBY0EX9gUQieudhLC5C0

      WevWWwedOVAuRp76t7zRzGs3EYxD5sy8q0bcyVMZCv5qg3fHSs9doi+ODUOn

      P2lJn0ITl/Hv0R6yCjRmCkLvBcMcsz+a8v1m++mQqQ6ZnJOLGPk='
  - secure: ! 'QzNUXCebiwMuVNXA38CBI26Vt1gTRbAXauDhHTnnStik7LEKTX5/4KTLzBXd

      SJS1JjFMkgD9vT8yCWqCPel4kbWb7seCA9fiI5kVeRExLw1GT1g4CMNnHAgk

      ImZTtqlufiLQsNPPJKY9pwqr7qLZh90BXHoLnmnQUD9ZH7CDTo0='
  - secure: ! 'TP4Alsm2+tfLxzH73nDJsYKUMKujpHazi6RyH5Ma+m7s3PSh8AstjQWhHbFX

      uTxJmGMMtMLobIeprI5DZKq/BQ6QtFiq+lncb6UoUg9PcptXFqTcXsPEy71A

      kkFcUNl2jJmsG/sxZ5uY0YcPpq+x44xgAbfXieL14QWX9qhv+3Y='
  - secure: ! 'GIPiARfD+UFM+NLsXCdSrsvsk9oude7jMENKiNQxLLVhQxDdB+Ezffv2U0xo

      bul8WM511xc1U06xHhn91FhEsVKbs+V5FC1xfwlNZVTcfIgwM+WBmdQOqmux

      oz0a9qE+1Cb3fHx+9LHKAEZstcaAdeze5LzF8P/iGtJoTKpGAgY='
